"""IELTS Academic Writing Task 2 — Prompt bank & metadata generator.

180+ curated prompts across 5 essay families × 12 topic domains.
Every prompt follows IELTS authenticity rules:
  - Sounds like a real IELTS public-issue question
  - Internationally accessible and debatable
  - Allows multiple legitimate positions
  - Does not require specialist knowledge
  - Uses concise IELTS-like phrasing
"""

import random

# ── Essay families ────────────────────────────────────────────────────────────

ESSAY_TYPES = [
    "opinion",
    "discussion",
    "problem_solution",
    "advantages_disadvantages",
    "two_part",
]

# ── Topic domains ─────────────────────────────────────────────────────────────

DOMAINS = [
    "education", "technology", "environment", "health",
    "society", "economy", "culture", "government",
    "work", "media", "crime", "urbanization",
]

# ── Prompt bank (180+ prompts) ────────────────────────────────────────────────
#
# Each prompt: {id, topic_title, essay_type, domain, statement, instruction,
#   abstraction_level, idea_load, wording_style, task_requirements, trap_flags}

WRITING_PROMPTS = [
    # ═══════════════════════════════════════════════════════════════════════════
    # OPINION — "To what extent do you agree or disagree?"
    # ═══════════════════════════════════════════════════════════════════════════

    # education
    {"id": "op_edu_01", "topic_title": "Free University Education", "essay_type": "opinion", "domain": "education",
     "statement": "Some people believe that university education should be free for all students, regardless of their financial background.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_edu_02", "topic_title": "Early Foreign Language Learning", "essay_type": "opinion", "domain": "education",
     "statement": "Children should begin learning a foreign language as soon as they start school.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_edu_03", "topic_title": "Exams as Fair Assessment", "essay_type": "opinion", "domain": "education",
     "statement": "Examinations are the fairest way to assess a student's ability.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},

    # technology
    {"id": "op_tech_01", "topic_title": "Internet & Social Isolation", "essay_type": "opinion", "domain": "technology",
     "statement": "The widespread use of the internet has made people more isolated from one another.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_tech_02", "topic_title": "AI Replacing Human Workers", "essay_type": "opinion", "domain": "technology",
     "statement": "Robots and artificial intelligence will eventually replace most human workers.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_tech_03", "topic_title": "Children's Tech Dependence", "essay_type": "opinion", "domain": "technology",
     "statement": "Children today are too dependent on computers and electronic entertainment.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},

    # environment
    {"id": "op_env_01", "topic_title": "Fuel Cost & Environment", "essay_type": "opinion", "domain": "environment",
     "statement": "The most effective way to deal with environmental problems is to increase the cost of fuel for cars and other vehicles.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_env_02", "topic_title": "Individual vs Government Action", "essay_type": "opinion", "domain": "environment",
     "statement": "Individuals can do nothing to improve the environment; only governments and large companies can make a real difference.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "nuanced",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position", "high_risk_of_partial_response"]},
    {"id": "op_env_03", "topic_title": "Economic Growth vs Environment", "essay_type": "opinion", "domain": "environment",
     "statement": "Economic growth is the only way to end world poverty, even if it harms the environment.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "nuanced",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},

    # health
    {"id": "op_hea_01", "topic_title": "Taxing Unhealthy Food", "essay_type": "opinion", "domain": "health",
     "statement": "Governments should make unhealthy food more expensive to encourage people to eat healthily.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_hea_02", "topic_title": "Prevention vs Treatment", "essay_type": "opinion", "domain": "health",
     "statement": "Prevention is better than cure, so health education is more important than treatment.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_hea_03", "topic_title": "Unhealthy Lifestyle & Healthcare Costs", "essay_type": "opinion", "domain": "health",
     "statement": "People who adopt an unhealthy lifestyle should pay more for their healthcare.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},

    # society
    {"id": "op_soc_01", "topic_title": "Family Meals Disappearing", "essay_type": "opinion", "domain": "society",
     "statement": "In many countries, the tradition of families eating meals together is disappearing.",
     "instruction": "To what extent do you think this is a negative development?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "balanced",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_soc_02", "topic_title": "Growing Wealth Inequality", "essay_type": "opinion", "domain": "society",
     "statement": "The gap between the rich and the poor is growing in many countries. This is inevitable in a modern economy.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "nuanced",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_soc_03", "topic_title": "Migration & Community Impact", "essay_type": "opinion", "domain": "society",
     "statement": "People today move to new cities or countries more often than in the past. This has a largely negative impact on communities.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},

    # economy
    {"id": "op_eco_01", "topic_title": "Domestic vs International Aid", "essay_type": "opinion", "domain": "economy",
     "statement": "Some people believe that the government should not spend money on international aid when there are disadvantaged people in their own country.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_eco_02", "topic_title": "Small Business Decline", "essay_type": "opinion", "domain": "economy",
     "statement": "Small businesses are disappearing because they cannot compete with large multinational companies.",
     "instruction": "To what extent do you agree or disagree that this is a negative development?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_eco_03", "topic_title": "Compulsory Community Service", "essay_type": "opinion", "domain": "economy",
     "statement": "Unpaid community service should be a compulsory part of high school programmes.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},

    # culture
    {"id": "op_cul_01", "topic_title": "Travel & Cultural Homogeneity", "essay_type": "opinion", "domain": "culture",
     "statement": "As international travel becomes cheaper and more convenient, it is inevitable that all cultures will eventually become the same.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "nuanced",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_cul_02", "topic_title": "Preserving Minority Languages", "essay_type": "opinion", "domain": "culture",
     "statement": "Governments should invest in preserving minority languages, even if very few people speak them.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_cul_03", "topic_title": "Free Museums & Galleries", "essay_type": "opinion", "domain": "culture",
     "statement": "Museums and art galleries should be free of charge for everyone, including tourists.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},

    # government
    {"id": "op_gov_01", "topic_title": "Privatising Public Services", "essay_type": "opinion", "domain": "government",
     "statement": "Some people think that all public services should be privatised, while others believe they should remain under government control.",
     "instruction": "To what extent do you agree that public services should be privatised?",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "balanced",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_gov_02", "topic_title": "Railways vs Roads Spending", "essay_type": "opinion", "domain": "government",
     "statement": "Governments should spend more money on railways rather than roads.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_gov_03", "topic_title": "Lowering the Voting Age", "essay_type": "opinion", "domain": "government",
     "statement": "The voting age should be lowered to sixteen in all countries.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},

    # work
    {"id": "op_wrk_01", "topic_title": "Remote Work Productivity", "essay_type": "opinion", "domain": "work",
     "statement": "People who work from home are more productive than those who work in an office.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_wrk_02", "topic_title": "Job Satisfaction vs Salary", "essay_type": "opinion", "domain": "work",
     "statement": "It is more important to enjoy your job than to earn a large salary.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_wrk_03", "topic_title": "Allowing Work From Home", "essay_type": "opinion", "domain": "work",
     "statement": "Employers should allow their workers to do some of their work from home.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},

    # media
    {"id": "op_med_01", "topic_title": "Social Media Harm to Society", "essay_type": "opinion", "domain": "media",
     "statement": "Social media does more harm than good to society.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_med_02", "topic_title": "News Objectivity & Opinion", "essay_type": "opinion", "domain": "media",
     "statement": "News organisations should be required to report only facts and should not be allowed to express opinions.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_med_03", "topic_title": "Banning Ads Aimed at Children", "essay_type": "opinion", "domain": "media",
     "statement": "Advertising aimed at children should be banned.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},

    # crime
    {"id": "op_cri_01", "topic_title": "Longer Prison Sentences", "essay_type": "opinion", "domain": "crime",
     "statement": "The best way to reduce crime is to give longer prison sentences.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_cri_02", "topic_title": "Young Offenders in Adult Courts", "essay_type": "opinion", "domain": "crime",
     "statement": "Young offenders should be treated the same as adult criminals in the justice system.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_cri_03", "topic_title": "Community Service vs Prison", "essay_type": "opinion", "domain": "crime",
     "statement": "Community service is a more effective punishment than imprisonment for minor offences.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},

    # urbanization
    {"id": "op_urb_01", "topic_title": "Discouraging City Migration", "essay_type": "opinion", "domain": "urbanization",
     "statement": "Living in a large city is becoming increasingly difficult. Governments should discourage people from moving to cities and encourage them to live in rural areas.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_urb_02", "topic_title": "Free Public Transport", "essay_type": "opinion", "domain": "urbanization",
     "statement": "Public transport should be made free in order to reduce traffic congestion in major cities.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},
    {"id": "op_urb_03", "topic_title": "Green Building Standards", "essay_type": "opinion", "domain": "urbanization",
     "statement": "All new buildings should be required to meet strict environmental standards, even if this increases construction costs.",
     "instruction": "To what extent do you agree or disagree?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["clear_position", "supported_arguments"],
     "trap_flags": ["requires_clear_position"]},

    # ═══════════════════════════════════════════════════════════════════════════
    # DISCUSSION — "Discuss both views and give your own opinion."
    # ═══════════════════════════════════════════════════════════════════════════

    # education
    {"id": "di_edu_01", "topic_title": "Schools: Social vs Academic Role", "essay_type": "discussion", "domain": "education",
     "statement": "Some people think that schools should teach children how to be good members of society. Others believe that the purpose of school is purely academic.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_edu_02", "topic_title": "University Access & Grades", "essay_type": "discussion", "domain": "education",
     "statement": "Some people believe that all university courses should be available to all students. Others think that universities should only offer places to students with good secondary school grades.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_edu_03", "topic_title": "Parents vs Schools: Social Skills", "essay_type": "discussion", "domain": "education",
     "statement": "Some people think that parents should teach children how to be good members of society. Others believe that school is the best place for this.",
     "instruction": "Discuss both these views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "low", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},

    # technology
    {"id": "di_tech_01", "topic_title": "Technology & Life Complexity", "essay_type": "discussion", "domain": "technology",
     "statement": "Some people believe that technology has made our lives too complex, and the solution is to live a simpler life without technology. Others disagree.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_tech_02", "topic_title": "Tech Impact on Literacy", "essay_type": "discussion", "domain": "technology",
     "statement": "Some people think that the increasing use of computers and mobile phones for communication has had a negative effect on young people's reading and writing skills. Others believe that these technologies have improved literacy.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_tech_03", "topic_title": "Space Exploration Funding", "essay_type": "discussion", "domain": "technology",
     "statement": "Some people feel that the development of space technology should continue. Others believe that the money spent on space research could be better used elsewhere.",
     "instruction": "Discuss both these views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},

    # environment
    {"id": "di_env_01", "topic_title": "Fuel Price & Environment Solutions", "essay_type": "discussion", "domain": "environment",
     "statement": "Some people think that the best way to solve environmental problems is to increase the price of fuel. Others think that there are better alternative ways of solving these problems.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_env_02", "topic_title": "National vs International Action", "essay_type": "discussion", "domain": "environment",
     "statement": "Some people believe that environmental problems should be solved at the national level. Others argue that these problems can only be addressed at the international level.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_env_03", "topic_title": "Adapting vs Fighting Climate Change", "essay_type": "discussion", "domain": "environment",
     "statement": "Some people think that instead of preventing climate change, we need to find a way to live with it. Others believe that urgent action is still needed.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "nuanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},

    # health
    {"id": "di_hea_01", "topic_title": "Individual vs Government Health", "essay_type": "discussion", "domain": "health",
     "statement": "Some people believe that it is the responsibility of individuals to take care of their own health. Others think that the government should ensure the health of its citizens.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_hea_02", "topic_title": "Mental vs Physical Health Funding", "essay_type": "discussion", "domain": "health",
     "statement": "Some people think that mental health is just as important as physical health and should receive equal funding. Others believe that physical health should remain the priority.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_hea_03", "topic_title": "Healthcare Worker Salaries", "essay_type": "discussion", "domain": "health",
     "statement": "Some people believe that doctors and nurses should be paid high salaries to attract the best candidates. Others argue that healthcare workers should be motivated by a desire to help people, not money.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},

    # society
    {"id": "di_soc_01", "topic_title": "Older Generation's Wisdom", "essay_type": "discussion", "domain": "society",
     "statement": "Some people think that older generations have little to teach younger people. Others believe that traditional knowledge and experience remain valuable.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_soc_02", "topic_title": "Competitive Sports & Children", "essay_type": "discussion", "domain": "society",
     "statement": "Some people believe that competitive sports have a positive effect on children's education. Others think that competitive sports cause problems for young people.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_soc_03", "topic_title": "Consumer Choice & Progress", "essay_type": "discussion", "domain": "society",
     "statement": "Some people think that having a wide variety of consumer choices is a sign of progress. Others believe that too many choices create confusion and waste.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},

    # economy
    {"id": "di_eco_01", "topic_title": "Economic vs Environmental Priority", "essay_type": "discussion", "domain": "economy",
     "statement": "Some people think that economic progress is the most important goal for developing countries. Others argue that environmental protection should be the priority.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_eco_02", "topic_title": "Globalisation's Winners & Losers", "essay_type": "discussion", "domain": "economy",
     "statement": "Some people believe that international trade and globalisation benefit all countries. Others argue that globalisation primarily benefits wealthy nations.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_eco_03", "topic_title": "Government Support for Industry", "essay_type": "discussion", "domain": "economy",
     "statement": "Some people argue that the government should support failing industries to protect jobs. Others believe that unsuccessful businesses should be allowed to close.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},

    # culture
    {"id": "di_cul_01", "topic_title": "Art Funding vs Practical Spending", "essay_type": "discussion", "domain": "culture",
     "statement": "Some people believe that art and cultural activities are important for society. Others think that government money should be spent on more practical things.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_cul_02", "topic_title": "Globalisation & Cultural Identity", "essay_type": "discussion", "domain": "culture",
     "statement": "Some people believe that globalisation leads to a loss of cultural identity. Others think that it helps cultures develop and evolve.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_cul_03", "topic_title": "Preserving Traditions & Festivals", "essay_type": "discussion", "domain": "culture",
     "statement": "Some people think that it is important to maintain traditional customs and festivals. Others believe that societies should focus on moving forward.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},

    # government
    {"id": "di_gov_01", "topic_title": "Science Funding vs Immediate Needs", "essay_type": "discussion", "domain": "government",
     "statement": "Some people think that governments should spend as much money as possible on developing science and technology. Others believe that this money should be spent on solving more immediate problems.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_gov_02", "topic_title": "Strict Laws vs Personal Freedom", "essay_type": "discussion", "domain": "government",
     "statement": "Some people think that strict laws are needed to control what people can and cannot do. Others think that people should be free to choose their own behaviour.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_gov_03", "topic_title": "Born vs Made Leaders", "essay_type": "discussion", "domain": "government",
     "statement": "Some people believe that leaders are born with natural talent. Others think that leadership skills can be learned.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "abstract", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},

    # work
    {"id": "di_wrk_01", "topic_title": "Set Retirement Age", "essay_type": "discussion", "domain": "work",
     "statement": "Some people think that having a set retirement age is necessary. Others believe that people should be allowed to continue working for as long as they want to.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_wrk_02", "topic_title": "One Job vs Changing Careers", "essay_type": "discussion", "domain": "work",
     "statement": "Some people argue that it is better to have one job for life. Others think that changing jobs frequently is beneficial.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_wrk_03", "topic_title": "Individual vs State Pensions", "essay_type": "discussion", "domain": "work",
     "statement": "Some people think that it is the responsibility of individuals to save for their own retirement. Others believe that the government should provide a pension for all citizens.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},

    # media
    {"id": "di_med_01", "topic_title": "Internet Regulation & Free Speech", "essay_type": "discussion", "domain": "media",
     "statement": "Some people think that the government should regulate the internet to prevent the spread of misinformation. Others believe that the internet should remain unregulated.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_med_02", "topic_title": "Print vs Electronic Media", "essay_type": "discussion", "domain": "media",
     "statement": "Some people think that traditional newspapers and books will be replaced by electronic media. Others believe that printed materials will always have a place.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_med_03", "topic_title": "Celebrity Role Model Duty", "essay_type": "discussion", "domain": "media",
     "statement": "Some people believe that celebrities have a responsibility to be good role models. Others think that they are just entertainers and should not be expected to set an example.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},

    # crime
    {"id": "di_cri_01", "topic_title": "Prison: Punishment vs Rehabilitation", "essay_type": "discussion", "domain": "crime",
     "statement": "Some people believe that the main purpose of prison is to punish criminals. Others think that rehabilitation and education are more important.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_cri_02", "topic_title": "Surveillance Cameras & Privacy", "essay_type": "discussion", "domain": "crime",
     "statement": "Some people think that the use of surveillance cameras in public places is an effective way to reduce crime. Others argue that it is an invasion of privacy.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_cri_03", "topic_title": "Death Penalty as Deterrent", "essay_type": "discussion", "domain": "crime",
     "statement": "Some people believe that the death penalty is necessary as a deterrent to serious crime. Others argue that it should be abolished in all countries.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},

    # urbanization
    {"id": "di_urb_01", "topic_title": "Houses vs Apartments", "essay_type": "discussion", "domain": "urbanization",
     "statement": "Some people prefer to live in a house, while others feel that there are more advantages to living in an apartment.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_urb_02", "topic_title": "Industry vs Tourism Development", "essay_type": "discussion", "domain": "urbanization",
     "statement": "Some people think that developing countries should focus on improving industrial capacity. Others believe that developing the tourism industry would be more beneficial.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},
    {"id": "di_urb_03", "topic_title": "Countryside vs City Expansion", "essay_type": "discussion", "domain": "urbanization",
     "statement": "Some people think that new towns and housing should be built in the countryside. Others believe that existing cities should be developed further.",
     "instruction": "Discuss both views and give your own opinion.",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["both_views", "own_opinion"],
     "trap_flags": ["requires_balanced_discussion", "requires_own_opinion"]},

    # ═══════════════════════════════════════════════════════════════════════════
    # PROBLEM-SOLUTION — "What are the causes/problems? What solutions?"
    # ═══════════════════════════════════════════════════════════════════════════

    # education
    {"id": "ps_edu_01", "topic_title": "School Leavers & Life Skills", "essay_type": "problem_solution", "domain": "education",
     "statement": "Many young people today leave school without a basic understanding of how to manage their personal finances.",
     "instruction": "Why is this the case? What can be done to address this problem?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},
    {"id": "ps_edu_02", "topic_title": "Declining Science Enrolment", "essay_type": "problem_solution", "domain": "education",
     "statement": "In many countries, the number of students choosing to study science subjects at university is declining.",
     "instruction": "What are the reasons for this trend? What measures could be taken to reverse it?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},
    {"id": "ps_edu_03", "topic_title": "Rise of Home Schooling", "essay_type": "problem_solution", "domain": "education",
     "statement": "In some countries, an increasing number of people are choosing to educate their children at home rather than sending them to school.",
     "instruction": "What are the reasons for this? Do you think this is a positive or negative development?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["causes_or_problems", "evaluation"],
     "trap_flags": ["requires_both_causes_and_solutions"]},

    # technology
    {"id": "ps_tech_01", "topic_title": "Online Personal Data Risks", "essay_type": "problem_solution", "domain": "technology",
     "statement": "The amount of personal information held on computers and shared on the internet is increasing rapidly.",
     "instruction": "What problems does this cause? What can be done to reduce the risks?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},
    {"id": "ps_tech_02", "topic_title": "Smartphone Overuse", "essay_type": "problem_solution", "domain": "technology",
     "statement": "Many people spend an increasing amount of time using their smartphones and other devices.",
     "instruction": "What problems does this cause? What solutions can you suggest?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},
    {"id": "ps_tech_03", "topic_title": "Automation & Job Losses", "essay_type": "problem_solution", "domain": "technology",
     "statement": "The widespread use of automated systems means that fewer people are required for many types of work.",
     "instruction": "What problems does this cause for society? How should governments respond?",
     "abstraction_level": "mixed", "idea_load": "high", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},

    # environment
    {"id": "ps_env_01", "topic_title": "Endangered Species & Extinction", "essay_type": "problem_solution", "domain": "environment",
     "statement": "Many species of plants and animals are endangered and at risk of extinction.",
     "instruction": "What are the causes of this? What measures can be taken to prevent it?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},
    {"id": "ps_env_02", "topic_title": "Urban Air Quality Decline", "essay_type": "problem_solution", "domain": "environment",
     "statement": "In many cities around the world, air quality is deteriorating to dangerous levels.",
     "instruction": "What are the main causes of this problem? What steps can governments and individuals take to improve the situation?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},
    {"id": "ps_env_03", "topic_title": "Rising Household Waste", "essay_type": "problem_solution", "domain": "environment",
     "statement": "The amount of waste produced by households continues to increase in many countries.",
     "instruction": "What are the reasons for this? What can be done to reverse this trend?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},

    # health
    {"id": "ps_hea_01", "topic_title": "Rising Obesity Rates", "essay_type": "problem_solution", "domain": "health",
     "statement": "In many countries, the number of overweight people, including children, is increasing at an alarming rate.",
     "instruction": "What are the causes of this problem? What solutions can be suggested?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},
    {"id": "ps_hea_02", "topic_title": "Stress-Related Illness", "essay_type": "problem_solution", "domain": "health",
     "statement": "Stress-related illnesses are becoming increasingly common in many countries.",
     "instruction": "What are the main causes of this problem? What can be done to address it?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},
    {"id": "ps_hea_03", "topic_title": "Rural Healthcare Access", "essay_type": "problem_solution", "domain": "health",
     "statement": "Despite improvements in healthcare, many people in rural areas still have limited access to medical services.",
     "instruction": "Why is this the case? What can be done to improve access to healthcare in these areas?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},

    # society
    {"id": "ps_soc_01", "topic_title": "Social Isolation & Community", "essay_type": "problem_solution", "domain": "society",
     "statement": "In many countries, people are living increasingly isolated lives, with less contact with their neighbours and community.",
     "instruction": "What are the causes of this? What can be done to encourage a stronger sense of community?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},
    {"id": "ps_soc_02", "topic_title": "Elderly Loneliness", "essay_type": "problem_solution", "domain": "society",
     "statement": "Many elderly people in developed countries are living alone and often feel lonely and neglected.",
     "instruction": "What are the reasons for this? What can society do to address this issue?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},
    {"id": "ps_soc_03", "topic_title": "Youth Housing Affordability", "essay_type": "problem_solution", "domain": "society",
     "statement": "Many young people today find it increasingly difficult to afford housing in major cities.",
     "instruction": "What are the causes of this situation? What measures can be taken to address it?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},

    # economy
    {"id": "ps_eco_01", "topic_title": "Youth Unemployment", "essay_type": "problem_solution", "domain": "economy",
     "statement": "Youth unemployment is a growing problem in many parts of the world.",
     "instruction": "What are the causes of this? What solutions can you suggest?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},
    {"id": "ps_eco_02", "topic_title": "Cost of Living vs Wages", "essay_type": "problem_solution", "domain": "economy",
     "statement": "The gap between the cost of living and average wages is widening in many countries.",
     "instruction": "What problems does this cause? What can governments do to address this issue?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},
    {"id": "ps_eco_03", "topic_title": "Brain Drain & Emigration", "essay_type": "problem_solution", "domain": "economy",
     "statement": "Many people are choosing to leave their home countries to seek better employment opportunities abroad.",
     "instruction": "What problems does this cause for their home countries? What can be done to encourage people to stay?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},

    # culture
    {"id": "ps_cul_01", "topic_title": "Traditional Skills Disappearing", "essay_type": "problem_solution", "domain": "culture",
     "statement": "Many traditional skills and ways of life are being lost as the world becomes more modernised.",
     "instruction": "What are the reasons for this? How can we preserve important aspects of traditional culture?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},

    # government
    {"id": "ps_gov_01", "topic_title": "Declining Trust in Government", "essay_type": "problem_solution", "domain": "government",
     "statement": "Public trust in governments and politicians has been declining in many countries.",
     "instruction": "What are the causes of this trend? What measures could be taken to restore public confidence?",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},

    # work
    {"id": "ps_wrk_01", "topic_title": "Job Dissatisfaction & Work-Life", "essay_type": "problem_solution", "domain": "work",
     "statement": "Many employees today report high levels of job dissatisfaction and poor work-life balance.",
     "instruction": "What are the causes of this problem? What can employers and individuals do to improve the situation?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},

    # media
    {"id": "ps_med_01", "topic_title": "Social Media Misinformation", "essay_type": "problem_solution", "domain": "media",
     "statement": "The spread of misinformation through social media has become a serious concern in many countries.",
     "instruction": "What problems does this cause? What can be done to deal with this issue?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},

    # crime
    {"id": "ps_cri_01", "topic_title": "Rising Crime Despite Penalties", "essay_type": "problem_solution", "domain": "crime",
     "statement": "Despite harsher penalties, the rate of crime in many countries continues to rise.",
     "instruction": "What are the possible causes of this? What other measures might be more effective in reducing crime?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},

    # urbanization
    {"id": "ps_urb_01", "topic_title": "Urban Traffic Congestion", "essay_type": "problem_solution", "domain": "urbanization",
     "statement": "Traffic congestion is a growing problem in most cities around the world.",
     "instruction": "What are the causes of this? What solutions can you suggest?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["causes_or_problems", "solutions"],
     "trap_flags": ["requires_both_causes_and_solutions"]},

    # ═══════════════════════════════════════════════════════════════════════════
    # ADVANTAGES-DISADVANTAGES — "Do the advantages outweigh the disadvantages?"
    # ═══════════════════════════════════════════════════════════════════════════

    # education
    {"id": "ad_edu_01", "topic_title": "Specialising vs Broad Subjects", "essay_type": "advantages_disadvantages", "domain": "education",
     "statement": "In some countries, students are required to study a wide range of subjects at school, while in others they can choose to specialise in fewer subjects.",
     "instruction": "What are the advantages and disadvantages of specialising in fewer subjects at school?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["advantages", "disadvantages"],
     "trap_flags": ["requires_both_sides"]},
    {"id": "ad_edu_02", "topic_title": "Online vs Classroom Learning", "essay_type": "advantages_disadvantages", "domain": "education",
     "statement": "Online learning has become increasingly popular in recent years, with many universities and schools offering courses entirely over the internet.",
     "instruction": "What are the advantages and disadvantages of online learning compared to traditional classroom education?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["advantages", "disadvantages"],
     "trap_flags": ["requires_both_sides"]},
    {"id": "ad_edu_03", "topic_title": "English-Only University Courses", "essay_type": "advantages_disadvantages", "domain": "education",
     "statement": "Some universities now offer all their courses in English, even in countries where English is not the official language.",
     "instruction": "Do the advantages of this outweigh the disadvantages?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["advantages", "disadvantages", "outweigh_judgment"],
     "trap_flags": ["requires_both_sides", "requires_outweigh_judgment"]},

    # technology
    {"id": "ad_tech_01", "topic_title": "Personal Devices at Work", "essay_type": "advantages_disadvantages", "domain": "technology",
     "statement": "Many companies now allow their employees to use personal electronic devices for work purposes.",
     "instruction": "Do the advantages of this trend outweigh the disadvantages?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["advantages", "disadvantages", "outweigh_judgment"],
     "trap_flags": ["requires_both_sides", "requires_outweigh_judgment"]},
    {"id": "ad_tech_02", "topic_title": "Self-Driving Cars", "essay_type": "advantages_disadvantages", "domain": "technology",
     "statement": "Self-driving cars are expected to become widely available in the near future.",
     "instruction": "What are the potential advantages and disadvantages of this development?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["advantages", "disadvantages"],
     "trap_flags": ["requires_both_sides"]},
    {"id": "ad_tech_03", "topic_title": "Cashless Society", "essay_type": "advantages_disadvantages", "domain": "technology",
     "statement": "More and more people are using cashless payment methods instead of cash.",
     "instruction": "Do the advantages of a cashless society outweigh the disadvantages?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["advantages", "disadvantages", "outweigh_judgment"],
     "trap_flags": ["requires_both_sides", "requires_outweigh_judgment"]},

    # environment
    {"id": "ad_env_01", "topic_title": "Nuclear Power Pros & Cons", "essay_type": "advantages_disadvantages", "domain": "environment",
     "statement": "Many countries are now investing heavily in nuclear power as an alternative to fossil fuels.",
     "instruction": "Do the advantages of nuclear energy outweigh the disadvantages?",
     "abstraction_level": "mixed", "idea_load": "high", "wording_style": "direct",
     "task_requirements": ["advantages", "disadvantages", "outweigh_judgment"],
     "trap_flags": ["requires_both_sides", "requires_outweigh_judgment"]},
    {"id": "ad_env_02", "topic_title": "Congestion Charges & Parking Fees", "essay_type": "advantages_disadvantages", "domain": "environment",
     "statement": "Some governments are encouraging their citizens to reduce their use of private cars by introducing congestion charges and higher parking fees.",
     "instruction": "What are the advantages and disadvantages of such measures?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["advantages", "disadvantages"],
     "trap_flags": ["requires_both_sides"]},

    # health
    {"id": "ad_hea_01", "topic_title": "Government-Funded Healthcare", "essay_type": "advantages_disadvantages", "domain": "health",
     "statement": "In some countries, healthcare is provided free of charge by the government, while in others, individuals must pay for their own medical treatment.",
     "instruction": "What are the advantages and disadvantages of government-funded healthcare?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["advantages", "disadvantages"],
     "trap_flags": ["requires_both_sides"]},
    {"id": "ad_hea_02", "topic_title": "Genetic Testing Ethics", "essay_type": "advantages_disadvantages", "domain": "health",
     "statement": "Genetic testing can now identify whether a person is likely to develop certain diseases in the future.",
     "instruction": "Do the advantages of genetic testing outweigh the disadvantages?",
     "abstraction_level": "mixed", "idea_load": "high", "wording_style": "direct",
     "task_requirements": ["advantages", "disadvantages", "outweigh_judgment"],
     "trap_flags": ["requires_both_sides", "requires_outweigh_judgment"]},

    # society
    {"id": "ad_soc_01", "topic_title": "Living Alone Trend", "essay_type": "advantages_disadvantages", "domain": "society",
     "statement": "More and more people are choosing to live alone rather than with family members or housemates.",
     "instruction": "Do the advantages of living alone outweigh the disadvantages?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["advantages", "disadvantages", "outweigh_judgment"],
     "trap_flags": ["requires_both_sides", "requires_outweigh_judgment"]},
    {"id": "ad_soc_02", "topic_title": "International Migration Impact", "essay_type": "advantages_disadvantages", "domain": "society",
     "statement": "International migration has increased significantly in recent decades.",
     "instruction": "What are the advantages and disadvantages of this trend for both the host countries and the countries of origin?",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "balanced",
     "task_requirements": ["advantages", "disadvantages"],
     "trap_flags": ["requires_both_sides", "high_risk_of_partial_response"]},

    # economy
    {"id": "ad_eco_01", "topic_title": "Tourism-Dependent Economies", "essay_type": "advantages_disadvantages", "domain": "economy",
     "statement": "Many countries now rely heavily on tourism as a major source of income.",
     "instruction": "What are the advantages and disadvantages of this dependence on tourism?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["advantages", "disadvantages"],
     "trap_flags": ["requires_both_sides"]},

    # work
    {"id": "ad_wrk_01", "topic_title": "Experience vs Fresh Graduates", "essay_type": "advantages_disadvantages", "domain": "work",
     "statement": "Many employers now prefer to hire people with work experience rather than fresh graduates.",
     "instruction": "What are the advantages and disadvantages of this approach for both employers and young people?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["advantages", "disadvantages"],
     "trap_flags": ["requires_both_sides"]},
    {"id": "ad_wrk_02", "topic_title": "Freelance Work Trend", "essay_type": "advantages_disadvantages", "domain": "work",
     "statement": "An increasing number of people are choosing to work as freelancers rather than in full-time employment.",
     "instruction": "Do the advantages of freelance work outweigh the disadvantages?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["advantages", "disadvantages", "outweigh_judgment"],
     "trap_flags": ["requires_both_sides", "requires_outweigh_judgment"]},

    # media
    {"id": "ad_med_01", "topic_title": "Social Media as News Source", "essay_type": "advantages_disadvantages", "domain": "media",
     "statement": "Many people now get their news from social media rather than from traditional news sources.",
     "instruction": "What are the advantages and disadvantages of this trend?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["advantages", "disadvantages"],
     "trap_flags": ["requires_both_sides"]},

    # urbanization
    {"id": "ad_urb_01", "topic_title": "Rural-to-Urban Youth Migration", "essay_type": "advantages_disadvantages", "domain": "urbanization",
     "statement": "In many countries, young people are moving from rural areas to cities in search of better opportunities.",
     "instruction": "Do the advantages of this trend outweigh the disadvantages?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["advantages", "disadvantages", "outweigh_judgment"],
     "trap_flags": ["requires_both_sides", "requires_outweigh_judgment"]},

    # ═══════════════════════════════════════════════════════════════════════════
    # TWO-PART — Two distinct questions about one topic
    # ═══════════════════════════════════════════════════════════════════════════

    # education
    {"id": "tp_edu_01", "topic_title": "Weight Gain & Declining Fitness", "essay_type": "two_part", "domain": "education",
     "statement": "In some countries, the average weight of people is increasing, and their levels of health and fitness are decreasing.",
     "instruction": "What do you think are the causes of these problems, and what measures could be taken to solve them?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},
    {"id": "tp_edu_02", "topic_title": "University vs Straight to Work", "essay_type": "two_part", "domain": "education",
     "statement": "Some people believe that studying at university or college is the best route to a successful career. Others believe that it is better to get a job straight after school.",
     "instruction": "When young people leave school, what do you think is the best option for them? Why?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},
    {"id": "tp_edu_03", "topic_title": "Education & Poverty Reduction", "essay_type": "two_part", "domain": "education",
     "statement": "Education is often considered the key to reducing poverty in developing countries.",
     "instruction": "Why is education important for economic development? What other factors contribute to reducing poverty?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},

    # technology
    {"id": "tp_tech_01", "topic_title": "Technology in the Classroom", "essay_type": "two_part", "domain": "technology",
     "statement": "Technology is increasingly being used in the classroom to support teaching and learning.",
     "instruction": "What are the benefits of using technology in education? Are there any drawbacks that need to be considered?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},
    {"id": "tp_tech_02", "topic_title": "Robots & Future Society", "essay_type": "two_part", "domain": "technology",
     "statement": "Scientists predict that in the future robots will do much of the work that humans currently do.",
     "instruction": "How might this change society? Do you think this is a positive or negative development?",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "balanced",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},
    {"id": "tp_tech_03", "topic_title": "Smartphone-Driven Social Change", "essay_type": "two_part", "domain": "technology",
     "statement": "Many people now use their smartphones for almost everything, from shopping to socialising.",
     "instruction": "How has this affected the way people interact with each other? Is this a positive or negative change?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},

    # environment
    {"id": "tp_env_01", "topic_title": "Global Water Scarcity", "essay_type": "two_part", "domain": "environment",
     "statement": "Fresh water has always been a limited resource in some parts of the world. Today, however, growing demand has made this a global problem.",
     "instruction": "What are the causes of the increased demand for water? What measures can governments and individuals take to respond to this problem?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},
    {"id": "tp_env_02", "topic_title": "Simple Living vs Tech Solutions", "essay_type": "two_part", "domain": "environment",
     "statement": "Some people believe that we should adopt a simpler way of life to address environmental problems, while others argue that technology is the key to solving them.",
     "instruction": "Which approach do you think is more effective? Why?",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "balanced",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},

    # health
    {"id": "tp_hea_01", "topic_title": "Increasing Life Expectancy", "essay_type": "two_part", "domain": "health",
     "statement": "In many developed countries, people are living longer than ever before.",
     "instruction": "What are the reasons for this? Is it entirely a positive development?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},
    {"id": "tp_hea_02", "topic_title": "Motivating Regular Exercise", "essay_type": "two_part", "domain": "health",
     "statement": "Regular physical exercise is essential for maintaining good health.",
     "instruction": "Why do many people fail to exercise regularly? What can be done to motivate them?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},

    # society
    {"id": "tp_soc_01", "topic_title": "Population Growth Impact", "essay_type": "two_part", "domain": "society",
     "statement": "The world is experiencing a dramatic increase in population.",
     "instruction": "What are the consequences of this? What measures can be taken to manage population growth?",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},
    {"id": "tp_soc_02", "topic_title": "Ageing Population Challenges", "essay_type": "two_part", "domain": "society",
     "statement": "In many countries, the proportion of older people is steadily increasing.",
     "instruction": "What effects will this have on society? How can governments prepare for the challenges of an ageing population?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},
    {"id": "tp_soc_03", "topic_title": "Career Choice & Family Pressure", "essay_type": "two_part", "domain": "society",
     "statement": "In some cultures, children are expected to follow the same career path as their parents.",
     "instruction": "Why does this happen? Do you think children should be free to choose their own careers?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},

    # economy
    {"id": "tp_eco_01", "topic_title": "Foreign Aid Effectiveness", "essay_type": "two_part", "domain": "economy",
     "statement": "Many developing countries are receiving foreign aid from wealthier nations.",
     "instruction": "Is this aid beneficial? What other approaches might help developing countries become self-sufficient?",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "balanced",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},
    {"id": "tp_eco_02", "topic_title": "Consumer Spending & Economy", "essay_type": "two_part", "domain": "economy",
     "statement": "Consumer spending is considered by many economists to be essential for a healthy economy.",
     "instruction": "Why is consumer spending important? Are there any negative consequences of a consumer-driven economy?",
     "abstraction_level": "abstract", "idea_load": "high", "wording_style": "balanced",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},

    # culture
    {"id": "tp_cul_01", "topic_title": "Learning Other Cultures", "essay_type": "two_part", "domain": "culture",
     "statement": "Learning about the history and culture of a country is important for understanding its people.",
     "instruction": "How can people best learn about the culture of another country? Why is this understanding important?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},
    {"id": "tp_cul_02", "topic_title": "Youth & Traditional Art Forms", "essay_type": "two_part", "domain": "culture",
     "statement": "In many countries, young people are losing interest in traditional music and art forms.",
     "instruction": "Why is this happening? What can be done to encourage young people to appreciate traditional culture?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},

    # government
    {"id": "tp_gov_01", "topic_title": "Declining City Quality of Life", "essay_type": "two_part", "domain": "government",
     "statement": "The quality of life in many large cities is declining.",
     "instruction": "What are the causes of this problem? What measures should be taken by cities and their governments?",
     "abstraction_level": "mixed", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},

    # work
    {"id": "tp_wrk_01", "topic_title": "Technology & Workplace Change", "essay_type": "two_part", "domain": "work",
     "statement": "Many businesses today rely heavily on technology to operate.",
     "instruction": "How has this changed the way people work? Is this change positive or negative?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},
    {"id": "tp_wrk_02", "topic_title": "Leisure Time Shortage", "essay_type": "two_part", "domain": "work",
     "statement": "Many people today feel that they do not have enough leisure time.",
     "instruction": "Why has this happened? What can individuals and employers do to address this?",
     "abstraction_level": "concrete", "idea_load": "low", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},

    # media
    {"id": "tp_med_01", "topic_title": "Changing News Consumption", "essay_type": "two_part", "domain": "media",
     "statement": "The way people consume news has changed dramatically in recent years.",
     "instruction": "How has news consumption changed? Do you think these changes are positive or negative?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "balanced",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},

    # crime
    {"id": "tp_cri_01", "topic_title": "Rising Cybercrime Threat", "essay_type": "two_part", "domain": "crime",
     "statement": "Cybercrime is becoming an increasingly serious problem around the world.",
     "instruction": "What are the main types of cybercrime? What can be done to combat this growing threat?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},

    # urbanization
    {"id": "tp_urb_01", "topic_title": "Urban Homelessness", "essay_type": "two_part", "domain": "urbanization",
     "statement": "Homelessness is a significant issue in many major cities around the world.",
     "instruction": "What are the main causes of homelessness? What measures can governments take to reduce it?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},
    {"id": "tp_urb_02", "topic_title": "Urban Overcrowding", "essay_type": "two_part", "domain": "urbanization",
     "statement": "Cities around the world are becoming increasingly crowded.",
     "instruction": "What are the effects of overcrowding in urban areas? How can city planners address this issue?",
     "abstraction_level": "concrete", "idea_load": "medium", "wording_style": "direct",
     "task_requirements": ["answer_part_1", "answer_part_2"],
     "trap_flags": ["requires_answering_two_questions"]},
]


# ── Index helpers ─────────────────────────────────────────────────────────────

_BY_TYPE: dict[str, list[dict]] = {}
_BY_DOMAIN: dict[str, list[dict]] = {}
for _p in WRITING_PROMPTS:
    _BY_TYPE.setdefault(_p["essay_type"], []).append(_p)
    _BY_DOMAIN.setdefault(_p["domain"], []).append(_p)


def generate_metadata(
    avoid_topics: list[str] | None = None,
    avoid_domains: list[str] | None = None,
    avoid_types: list[str] | None = None,
) -> dict | None:
    """Pick a random writing prompt, avoiding recently used topics/domains/types.

    Returns prompt dict or None if nothing available (shouldn't happen with 180+ prompts).
    """
    avoid_t = set(avoid_topics or [])
    avoid_d = set(avoid_domains or [])
    avoid_ty = set(avoid_types or [])

    # Pool stores topic as topic_title, so compare against that
    candidates = [
        p for p in WRITING_PROMPTS
        if p["topic_title"] not in avoid_t
        and p["domain"] not in avoid_d
        and p["essay_type"] not in avoid_ty
    ]

    if not candidates:
        # Relax: only avoid topics
        candidates = [p for p in WRITING_PROMPTS if p["topic_title"] not in avoid_t]

    if not candidates:
        # Fully relax
        candidates = list(WRITING_PROMPTS)

    return random.choice(candidates) if candidates else None
